name = "vacation"
compatibility_date = "2025-03-25"
type = "javascript"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[vars]
DATABASE_URL = ""
NEXTAUTH_SECRET = ""
NEXTAUTH_URL = "https://vacation.alicoding.com"
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""

[env.production]
name = "vacation"
workers_dev = true

[env.development]
name = "vacation-dev"
workers_dev = true