name = "vacation"
compatibility_date = "2025-03-25"

[build]
command = "npm run build"
publish = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20"


[env.production]
name = "vacation"
workers_dev = true

[env.production.build.environment]

[env.development]
name = "vacation-dev"
workers_dev = true 