name = "vacation"
compatibility_date = "2025-03-25"

[assets]
directory = ".next/static"

[build]
command = "npm run build"
publish = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = ".vercel/output/static"

[vars]
# Replace with your actual production database URL
DATABASE_URL = "postgresql://user:pass@host:5432/dbname?schema=public"

[env.production]
name = "vacation"
workers_dev = true

[env.production.build.environment]

[env.development]
name = "vacation-dev"
workers_dev = true 