name = "vacation"
compatibility_date = "2025-04-02"
pages_build_output_dir = ".vercel/output"

[env.production]
vars = { 
  NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}", 
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}", 
  NEXTAUTH_URL = "${NEXTAUTH_URL}", 
  NEXTAUTH_SECRET = "${NEXTAUTH_SECRET}"
}